---
 # Pull application from git repository

- name: Setup ssh on remote to access git
  copy: src={{ git_ssh_key }} dest="/home/ec2-user/.ssh/mygitkey" 
        owner=ec2-user group=ec2-user mode=0600
- name: Download application code from git
  git: repo={{ git_app_repo }} dest="{{ app_root }}/app_code"
       key_file="/home/ec2-user/.ssh/mygitkey"
       accept_hostkey=yes
